#pragma once

#ifndef INTERNET_DEFAULT_HTTP_PORT
#define INTERNET_DEFAULT_HTTP_PORT 80
#endif // !INTERNET_DEFAULT_HTTP_PORT

#ifndef INTERNET_DEFAULT_HTTPS_PORT
#define INTERNET_DEFAULT_HTTPS_PORT 443
#endif // !INTERNET_DEFAULT_HTTPS_PORT

//#define RESERVE
#ifdef RESERVE
//#define RESERVE_DOMAIN "panellink"
#endif

//#define ONION_ROUTING

